language: generic

services:
  - docker

addons:
  apt:
    update: true
    packages:
      - curl
      - dirmngr
      - libdigest-sha-perl

env:
  - HADOLINT="${HOME}/hadolint"

install:
  - mkdir -p build
  # Install syft
  - sudo sh -c 'curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin'
  - syft version
  # Install grype
  - sudo sh -c 'curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin'
  - grype version
  # Install hadolint
  - curl -sL -o ${HADOLINT} "https://github.com/hadolint/hadolint/releases/download/v1.17.6/hadolint-$(uname -s)-$(uname -m)" && chmod 700 ${HADOLINT}
  - hadolint --version

jobs:
  include:
    - stage: build
      script:
        - bin/docker-build.sh
    - stage:
      script:
        - bin/docker-test.sh
