language: generic

services:
  - docker

before_install:
  # Install syft
  - sudo sh -c 'curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin'
  - syft version

script:
  - bin/docker-build.sh
