language: generic

services:
  - docker

addons:
  apt:
    update: true
    packages:
      - curl
      - dirmngr
      - libdigest-sha-perl

env:
  global:
    # Include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli

install:
  - mkdir -p build
  # Install syft
  - sudo sh -c 'curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin'
  - syft version
  # Install grype
  - sudo sh -c 'curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin'
  - grype version
  # Install hadolint
  - sudo sh -c 'curl -sL -o /usr/local/bin/hadolint "https://github.com/hadolint/hadolint/releases/download/v1.17.6/hadolint-$(uname -s)-$(uname -m)" && chmod 755 /usr/local/bin/hadolint'
  - hadolint --version

jobs:
  include:
    - stage: build
      script:
        - bin/get-binaries.sh
        - bin/docker-build.sh
    - stage: test
      script:
        - bin/docker-test.sh
