language: generic

services:
  - docker

before_install:
  # Install syft
  - curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

script:
  - bin/docker-build.sh
